# Generated by Django 4.2 on 2023-07-07 13:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, default='12.317277', null=True)),
                ('lng', models.FloatField(blank=True, default='78.713890', null=True)),
                ('alt', models.FloatField(blank=True, default=' 1500.0', null=True)),
                ('streetAddress', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('postalCode', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('fullAddress', models.CharField(blank=True, default='', max_length=320, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupDate', models.DateTimeField(blank=True, null=True)),
                ('pickedup', models.BooleanField(default=False)),
                ('dropDate', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docType', models.CharField(blank=True, choices=[('profile_photo', 'Profile Photo'), ('event_photo', 'Event Photo'), ('food_photo', 'Food Photo'), ('vehicle_photo', 'Vehicle Photo')], default='profile_photo', max_length=50, null=True)),
                ('document', models.FileField(blank=True, default='', null=True, upload_to='user/documents')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('organizerPhoneNumber', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('eventStartDate', models.DateTimeField(blank=True, null=True)),
                ('eventEndDate', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('additionalInfo', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.address')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(default='Food Name', max_length=100)),
                ('expiryDate', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='', max_length=300)),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('volunteerType', models.CharField(blank=True, choices=[('driver', 'Driver'), ('food_donor', 'Food Donor'), ('event_organizer', 'Event Organizer'), ('event_volunteer', 'Event Volunteer'), ('food_seeker', 'Food Seeker')], default='food_seeker', max_length=50, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('isVolunteer', models.BooleanField(blank=True, default=False, null=True)),
                ('isDriver', models.BooleanField(blank=True, default=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastLogin', models.DateTimeField(auto_now=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.address')),
            ],
            options={
                'verbose_name': 'Volunteer',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('plateNumber', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vehicleColour', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiredDate', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('fullfilled', models.BooleanField(blank=True, default=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.volunteer')),
                ('deliver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.deliverydetail')),
                ('foodEvent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.foodevent')),
                ('foodItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.fooditem')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.requesttype')),
            ],
        ),
        migrations.CreateModel(
            name='FoodRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ingredients', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('cookingInstructions', models.TextField(default='', max_length=500)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.category')),
                ('foodImage', models.ManyToManyField(blank=True, null=True, related_name='recipe_photos', to='app.document')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='addedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.volunteer'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.foodevent'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='itemPhotos',
            field=models.ManyToManyField(blank=True, null=True, related_name='food_photos', to='app.document'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='itemType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.itemtype'),
        ),
        migrations.AddField(
            model_name='foodevent',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_event_organiser', to='app.volunteer'),
        ),
        migrations.CreateModel(
            name='EventVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.foodevent')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.request')),
                ('volunteers', models.ManyToManyField(blank=True, null=True, related_name='event_volunteers', to='app.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='EventBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.foodevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('needsPickup', models.BooleanField(default=False)),
                ('fullfilled', models.BooleanField(blank=True, default=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.deliverydetail')),
                ('donatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_donor', to='app.volunteer')),
                ('donationType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.itemtype')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.foodevent')),
                ('foodItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.fooditem')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.request')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.foodevent'),
        ),
        migrations.AddField(
            model_name='document',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_photo', to='app.vehicle'),
        ),
        migrations.AddField(
            model_name='document',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_profile_img', to='app.volunteer'),
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.volunteer'),
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='dropAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drop_address', to='app.address'),
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='pickupAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_address', to='app.address'),
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(default='', max_length=255)),
                ('refreshToken', models.CharField(default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.volunteer')),
            ],
        ),
    ]
