# Generated by Django 4.2 on 2023-07-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodevent',
            name='eventPhoto',
            field=models.FileField(blank=True, default='', null=True, upload_to='user/documents'),
        ),
    ]
