# Generated by Django 4.2 on 2023-07-27 07:30

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_foodevent_eventphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, default='', null=True, upload_to='user/documents', validators=[app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='foodevent',
            name='eventPhoto',
            field=models.FileField(blank=True, default='', null=True, upload_to='user/documents', validators=[app.validators.validate_file_size]),
        ),
    ]
