# Generated by Django 4.2 on 2023-09-01 11:38

import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_document_document_alter_foodevent_eventphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryImage',
            field=models.FileField(blank=True, default='', null=True, upload_to='user/documents', validators=[app.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='customtoken',
            name='expoPushToken',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_recipe_img', to='app.foodrecipe'),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='preparationTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='recipeCredits',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='recipeSource',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='foodrecipe',
            name='category',
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='cookingInstructions',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='foodrecipe',
            name='foodImage',
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='ingredients',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(blank=True, default='title', max_length=50, null=True)),
                ('message', models.CharField(blank=True, default='this is sample message', max_length=255, null=True)),
                ('is_unread', models.BooleanField(default=True)),
                ('modifiedAt', models.DateTimeField(blank=True, null=True)),
                ('notificationType', models.CharField(blank=True, choices=[('event', 'Event'), ('donation', 'Donation'), ('other', 'Other')], default='other', max_length=50, null=True)),
                ('isDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipe_category', to='app.category'),
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='foodImage',
            field=models.FileField(blank=True, default='', null=True, upload_to='user/documents', validators=[app.validators.validate_file_size]),
        ),
    ]
