# Generated by Django 4.2 on 2023-12-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docType',
            field=models.CharField(blank=True, choices=[('profile_photo', 'Profile Photo'), ('event_photo', 'Event Photo'), ('food_photo', 'Food Photo'), ('vehicle_photo', 'Vehicle Photo'), ('event_sharing', 'Event Sharing'), ('volunteer_sharing', 'Volunteer Sharing')], default='profile_photo', max_length=50, null=True),
        ),
    ]
