name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clear Cache
        run: rm -rf ${{ runner.temp }}/*

      - name: Debug secrets
        run: |
          echo "EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}"
          echo "EC2_USERNAME: ${{ secrets.EC2_USERNAME }}"
          echo "EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/
            mkdir removethisdir
            source food-env/bin/activate
            cd foodhealers_backend/
            git checkout develop
            git pull origin develop
            pip install -r requirements.txt
            python manage.py makemigrations
            python manage.py migrate
            sudo systemctl restart foodhealers-gunicorn.service
            exit
