name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  zip_files:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip files
        run: zip -r foodhealers.zip . -x .gitignore -x .github -x .git/*

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: foodhealers
          path: foodhealers.zip

  s3_deployment:
    needs: zip_files
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: foodhealers
          path: .

      - name: Upload zip file to S3
        uses: actions/upload-artifact@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          DEST_FILE: foodhealers.zip
