name: Upload to AWS S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: foodhealers
        path: .    # The path here should be the current directory as the filename will be added automatically

    - name: Configure AWS credentials
      run: |
        mkdir -p $HOME/.aws
        echo "[default]" >> $HOME/.aws/credentials
        echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> $HOME/.aws/credentials
        echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> $HOME/.aws/credentials
        echo "region=$AWS_DEFAULT_REGION" >> $HOME/.aws/credentials

    - name: Install AWS CLI
      run: sudo apt-get -q install -y awscli

    - name: Upload to AWS S3
      run: |
        aws s3 cp ./foodhealers.zip s3://$BUCKET_NAME/
