name: Build and Push Docker Image

on:
  push:
    branches:
      - pipeline/dockerimage

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: aws login
        run: |
         aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
         aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
         aws s3 cp s3://pipeline-secrets-climatehealers/food-healers-b6ab8-firebase-adminsdk-dqe5w-9169a69607.json ./food-healers-b6ab8-firebase-adminsdk-dqe5w-9169a69607.json
         cat food-healers-b6ab8-firebase-adminsdk-dqe5w-9169a69607.json  # Verify the file content
         touch .local.env
         echo "${{ secrets.ENVFILE }}" >> .local.env
         cat .local.env

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/aravindmuniraj95/climatehealers/foodhealers-backends:v1 .
          docker login ghcr.io -u aravindmuniraj95 -p ${{ secrets.PAT_TOKEN }}
          docker push ghcr.io/aravindmuniraj95/climatehealers/foodhealers-backends:v1
