name: Build and Push Docker Image
on:
  push:
    branches:
      - pipeline/dockerimage

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run commands
        run: |
          touch local.json
          echo "${{ secrets.ENVFILE }}" >> local.json
          cat local.json
      - name: Build Docker image
        run: docker build -t ghcr.io/aravindmuniraj95/climatehealers/foodhealers-backends:v1 .

      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u aravindmuniraj95 -p ${{ secrets.PAT_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/aravindmuniraj95/climatehealers/foodhealers-backends:v1
