name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  zip_files:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip files
        run: zip -r foodhealers.zip . -x .gitignore -x .github -x .git/*

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: foodhealers
          path: foodhealers.zip

  upload:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: zip_files   # Wait for the "zip_files" job to finish before running this job.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: foodhealers
        path: foodhealers.zip

  s3_deployment:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: zip_files
    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Zip code
        run: zip -r foodhealers.zip . -x .gitignore -x .github -x .git/*
      - name: Copy files to S3
        run: aws s3 cp ./foodhealers.zip s3://foodhealers-backend-codepipeline-s3
