name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          ssh -i $SSH_PRIVATE_KEY ubuntu@EC2_PUBLIC_IP 'source /home/ubuntu/food-env/bin/activate && cd cd /home/ubuntu/foodhealers_backend/ && sudo systemctl restart foodhealers-gunicorn.service'

    - name: Finish pipeline
      run: echo "Deployment completed successfully"
