name: Build and Push Docker Image

on:
  push:
    branches:
      - pipeline/dockerimage

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: dockerbuildx
       uses: docker/setup-buildx-action@v1
     - name: s3download
       uses: keithweaver/aws-s3-github-action@v1.0.0
       with:
         command: cp
         source: s3://pipeline-secrets-climatehealers/food-healers-b6ab8-firebase-adminsdk-dqe5w-9169a69607.json
         destination: ./
         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws_region: ap-south-1
     - name: buildimage
       run: |
         touch .local.env
         echo "${{ secrets.ENVFILE }}" >> .local.env
         cat .local.env

     - name: Build Docker image
       run: |
          docker build -t ghcr.io/aravindmuniraj95/climatehealers/foodhealers-backends:v1 .
          docker login ghcr.io -u aravindmuniraj95 -p ${{ secrets.PAT_TOKEN }}
          docker push ghcr.io/aravindmuniraj95/climatehealers/foodhealers-backends:v1
