name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  s3_deployment:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Zip code
        run: zip -r foodhealers.zip .
      - name: Copy files to S3
        run: aws s3 cp ./foodhealers.zip s3://foodhealers-backend-codepipeline-s3
