name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  zip_files:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip files
        run: zip -r foodhealers.zip . -x .gitignore -x .github -x .git/*

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: foodhealers
          path: foodhealers.zip

  upload:
    runs-on: ubuntu-latest
    needs: zip_files   # Wait for the "zip_files" job to finish before running this job.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: foodhealers
        path: foodhealers.zip

    - name: Configure AWS credentials
      run: |
        mkdir -p $HOME/.aws
        echo "[default]" >> $HOME/.aws/credentials
        echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> $HOME/.aws/credentials
        echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> $HOME/.aws/credentials
        echo "region=$AWS_DEFAULT_REGION" >> $HOME/.aws/credentials

    - name: Install AWS CLI
      run: sudo apt-get -q install -y awscli

    - name: Upload to AWS S3
      run: |
        aws s3 cp ./foodhealers.zip s3://$BUCKET_NAME/
