name: Build and Push Docker Image

on:
  push:
    branches:
      - pipeline/dockerimage

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: create-json
       id: create-json
       uses: jsdaniell/create-json@1.1.2
       with:
          name: "food-healers-b6ab8-firebase-adminsdk-dqe5w-9169a69607.json"
          json: ${{ secrets.FIREBASE_JSON }}
     - name: buildimage
       run: |
         touch .local.env
         echo "${{ secrets.ENVFILE }}" >> .local.env
         cat .local.env

     - name: Build Docker image
       run: |
          docker build -t ghcr.io/aravindmuniraj95/climatehealers/foodhealers-backends:v1 .
          docker login ghcr.io -u aravindmuniraj95 -p ${{ secrets.PAT_TOKEN }}
          docker push ghcr.io/aravindmuniraj95/climatehealers/foodhealers-backends:v1
