name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Debug secrets
        run: |
          echo "EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}"
          echo "EC2_USERNAME: ${{ secrets.EC2_USERNAME }}"
          echo "EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            source /home/ubuntu/food-env/bin/activate
            cd /home/ubuntu/foodhealers_backend/
            sudo systemctl restart foodhealers-gunicorn.service
